import { defineConfig } from "oxlint";

const frontendConfig = defineConfig({
  plugins: ["vue"],
  env: {
    browser: true,
    node: true,
  },
  globals: {
    defineNuxtConfig: "readonly",
    defineNuxtPlugin: "readonly",
    definePageMeta: "readonly",
    defineRouteRules: "readonly",
    useRuntimeConfig: "readonly",
    useFetch: "readonly",
    useAsyncData: "readonly",
    useLazyFetch: "readonly",
    useLazyAsyncData: "readonly",
    useState: "readonly",
    useHead: "readonly",
    useSeoMeta: "readonly",
    useAppConfig: "readonly",
    navigateTo: "readonly",
    abortNavigation: "readonly",
    addRouteMiddleware: "readonly",
    callOnce: "readonly",
    clearError: "readonly",
    clearNuxtData: "readonly",
    clearNuxtState: "readonly",
    createError: "readonly",
    defineNuxtRouteMiddleware: "readonly",
    preloadComponents: "readonly",
    prefetchComponents: "readonly",
    refreshNuxtData: "readonly",
    setPageLayout: "readonly",
    setResponseHeader: "readonly",
    setResponseStatus: "readonly",
    showError: "readonly",
    useCookie: "readonly",
    useRequestEvent: "readonly",
    useRequestHeaders: "readonly",
    useRequestURL: "readonly",
    useRoute: "readonly",
    useRouter: "readonly",
    $fetch: "readonly",
    NuxtLink: "readonly",
    NuxtPage: "readonly",
    NuxtLayout: "readonly",
    NuxtErrorBoundary: "readonly",
    NuxtWelcome: "readonly",
    NuxtLoadingIndicator: "readonly",
  },
});

export default frontendConfig;
